play.http.secret.key = "z4N8w2Qm9Lp1Ts6Hv3Rx7Kc5Jd0Bf8Yn2Pw4Gq9Mz6"

play.modules.enabled += "play.api.db.DBModule"
play.modules.enabled += "play.api.db.HikariCPModule"

db.default.driver = "com.mysql.cj.jdbc.Driver"
db.default.url = "jdbc:mysql://localhost:3306/crud_play?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
db.default.username = "root"
db.default.password = "root"

play.http.filters = "Filters"

play.filters.hosts {
  allowed = ["."]
}

play.filters.cors {
  pathPrefixes = ["/"]
  allowedOrigins = null
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = null
  preflightMaxAge = 3600 seconds
}
